
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moklet
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        tglpinjam = new com.toedter.calendar.JDateChooser();
        tglkembali = new com.toedter.calendar.JDateChooser();
        exit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        print = new javax.swing.JButton();
        pelajaran = new javax.swing.JRadioButton();
        novel = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERPUSTAKAAN ARMANIA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 10, 400, 30);

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Open A Book, Open The World !!!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 50, 280, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -1, 810, 90);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tgl Kembali");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 260, 130, 35);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIS");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 20, 120, 35);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Siswa");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(140, 60, 120, 35);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kelas");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 100, 120, 35);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kategori Buku");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(140, 140, 120, 35);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Judul Buku");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 180, 120, 35);
        jPanel2.add(nis);
        nis.setBounds(300, 20, 200, 30);
        jPanel2.add(nama);
        nama.setBounds(300, 60, 200, 30);
        jPanel2.add(kelas);
        kelas.setBounds(300, 100, 200, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tgl Pinjam");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(140, 220, 120, 35);
        jPanel2.add(judul);
        judul.setBounds(300, 180, 200, 30);
        jPanel2.add(tglpinjam);
        tglpinjam.setBounds(300, 220, 200, 30);
        jPanel2.add(tglkembali);
        tglkembali.setBounds(300, 260, 200, 30);

        exit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(540, 240, 100, 30);

        save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(540, 40, 100, 30);

        edit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit);
        edit.setBounds(540, 80, 100, 30);

        clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);
        clear.setBounds(540, 120, 100, 30);

        delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(540, 160, 100, 30);

        print.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel2.add(print);
        print.setBounds(540, 200, 100, 30);

        buttonGroup2.add(pelajaran);
        pelajaran.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        pelajaran.setText("Pelajaran");
        jPanel2.add(pelajaran);
        pelajaran.setBounds(300, 140, 90, 30);

        buttonGroup2.add(novel);
        novel.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        novel.setText("Novel");
        jPanel2.add(novel);
        novel.setBounds(410, 140, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 810, 310);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "Kelas", "KategoriBuku", "JudulBuku", "TglPinjam", "TglKembali"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 30, 780, 180);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 390, 810, 240);

        setBounds(0, 0, 818, 668);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(tglpinjam.getDate());
        String kembali = dateFormat.format(tglkembali.getDate());
        
        if("".equals(nis.getText()) || "".equals(nama.getText()) ||
           "".equals(kelas.getText()) || "".equals(judul.getText()) || pinjam.equals("") || kembali.equals("")) 
        {
           JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String KB = "";
                if(pelajaran.isSelected()) {
                    KB = "Buku Pelajaran";
                }
                else{
                    KB = "Novel";
                }
            String SQL = "INSERT INTO tb_siswa (NIS,NamaSiswa,Kelas,KategoriBuku,JudulBuku,TglPinjam,TglKembali)"
                    + "VALUES('"+nis.getText()+"','"+nama.getText()+"','"+kelas.getText()+"','"+KB+"','"
                    + judul.getText()+"','"+pinjam+"','"+kembali+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       MessageFormat header = new MessageFormat("Peminjaman Buku Perpustakaan Armania");
       MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
       
       try{
           table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
       }
       catch (java.awt.print.PrinterException e){
           System.err.format("Cannot print %s%n ", e.getMessage());
       }
    }//GEN-LAST:event_printActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nis.setText("");
        nama.setText("");
        kelas.setText("");
        buttonGroup2.clearSelection();
        judul.setText("");
        tglpinjam.setCalendar(null);
        tglkembali.setCalendar(null);
    }//GEN-LAST:event_clearActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(tglpinjam.getDate());
        String kembali = dateFormat.format(tglkembali.getDate());
        
        int baris = table.getSelectedRow();
        if(baris != -1) {
            nis.setText(table.getValueAt(baris, 0).toString());
            nama.setText(table.getValueAt(baris, 1).toString());
            kelas.setText(table.getValueAt(baris, 2).toString());
            
        String kb = table.getValueAt(baris, 3).toString();
        if(kb.equals("Buku Pelajaran")){
            pelajaran.setSelected(true);
        }
        if(kb.equals("Novel"))
        {
            novel.setSelected(true);
        }   
            judul.setText(table.getValueAt(baris, 4).toString());
            pinjam = (table.getValueAt(baris, 5).toString());
            kembali = (table.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(tglpinjam.getDate());
        String kembali = dateFormat.format(tglkembali.getDate());
        
        int baris = table.getSelectedRow();
        String NIS = table.getValueAt(baris, 0).toString();
        
        if("".equals(nis.getText()) || "".equals(nama.getText()) ||
            "".equals(kelas.getText()) || "".equals(judul.getText())) {
         JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
         }
         else{
             String KB = "";
             if(pelajaran.isSelected()){
                 KB = "Buku Pelajaran";
             }
             else {
                 KB = "Novel";
             }
             
             String SQL = "UPDATE tb_siswa SET "
                     + "NamaSiswa='"+nama.getText()+"',"
                     + "Kelas='"+kelas.getText()+"',"
                     + "KategoriBuku='"+KB+"',"
                     + "JudulBuku='"+judul.getText()+"',"
                     + "tglpinjam='"+pinjam+"',"
                     + "tglkembali='"+kembali+"',"
                     + "WHERE NIS='"+nis.getText()+"'";
             int status = KoneksiDB.execute(SQL);
             if(status == 1){
                 JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                 selectData();
             }
             else{
                 JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
             }
         }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int baris = table.getSelectedRow();
        if (baris != -1){
            String id = table.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_siswa WHERE NIS='"+nis+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }

        selectData();
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JRadioButton novel;
    private javax.swing.JRadioButton pelajaran;
    private javax.swing.JButton print;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser tglkembali;
    private com.toedter.calendar.JDateChooser tglpinjam;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","Kelas","KategoriBuku","JudulBuku","TglPinjam","TglKembali"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String Kelas = rs.getString(3);
                String KB = "";
                if("Buku Pelajaran".equals(rs.getString(4))) {
                    KB = "Buku Pelajaran";
                }
                else{
                    KB = "Novel";
                }
                String JudulBuku = rs.getString(5);
                String TglPinjam = rs.getString(6);
                String TglKembali = rs.getString(7);
                String data[] = {NIS,NamaSiswa,Kelas,KB,JudulBuku,TglPinjam,TglKembali};
                dtm.addRow(data);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        table.setModel(dtm);
    }
}
